name: Build Vue
on:
  pull_request:
    branches:
      - main
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: eoussama/vue-pages-action@0.0.2
        with:
          username: 'KeganSpolidoro'
          reponame: 'Extended-Planning-Instrument-for-Unpredictable-Spaces-and-Environments'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
