name: APITESTS

on:
  pull_request:
    branches:
      - development
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install Newman
        run: npm install -g newman

      - name: Run Integration Tests
        run: newman run Tests/IntegrationTests.json
